version: "3.4"
services:
    frontend:
        image: robinlp1/cookie-frontend:${BUILD_TAG}
        ports:
            - 8080:8080    
        environment:
            - BACKEND_DNS=backend
            - "BUILD_TAG=${BUILD_TAG}"
    backend: 
        image: robinlp1/cookie-backend:${BUILD_TAG}
        environment:
            - "BUILD_TAG=${BUILD_TAG}"