version: "3.4"
services:
    frontend:
        image: robinlp1/cookie-frontend:latest
        ports:
            - 8080:8080
        environment:
            - BACKEND_DNS=backend
    backend: 
        image: robinlp1/cookie-backend:latest