version: "3"
services:
    frontend:
        depends_on:
            - backend
        image: robinlp1/cookie-frontend:latest
        ports:
            - "8080:8080"
    backend: 
        image: robinlp1/cookie-backend:latest
        ports:
            - "9000:9000"