version: "3.4"
services:
    frontend:
        image: robinlp1/cookie-frontend:${GIT_COMMIT}
        ports:
            - 8080:8080    
        environment:
            - BACKEND_DNS=backend
            - "GIT_COMMIT=${GIT_COMMIT}"
    backend: 
        image: robinlp1/cookie-backend:${GIT_COMMIT}
        environment:
            - "GIT_COMMIT=${GIT_COMMIT}"
    backend: 
        image: robinlp1/cookie-backend:latest
        environment:
            - REDIS_DNS=redis
    redis:
        image: redis:latest
