apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: c-backend
  name: c-backend
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: c-backend
  type: ClusterIP
status:
  loadBalancer: {}
