apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: c-redis
  name: c-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c-redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: c-redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        ports:
        - containerPort: 6379
        resources: {}
status: {}
