name: CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: dev-runner
    steps:
      - uses: actions/checkout@v2
      - name: run k8s
        run: |
          kubectl apply -f k8s/

  deploy-prod:
    runs-on: prod-runner
    steps:
      - uses: actions/checkout@v2
      - name: run k8s
        run: |
          kubectl apply -f k8s/
