name: CI

env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

on:
  pull_request:
    branches: [ main ]

jobs: 
  run-lint:
    runs-on: ubuntu-latest
    container: golang:1.17
    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
        cd frontend
        $(go env GOPATH)/bin/golangci-lint run -D errcheck -D gosimple
        cd ../backend
        $(go env GOPATH)/bin/golangci-lint run -D errcheck -D gosimple

  run-test:
    runs-on: ubuntu-latest
    container: golang:1.17
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: |
        cd frontend
        go test -v

  Docker-build-and-push-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build backend
        run: |
          cd backend
          export GIT_COMMIT="GA-${GITHUB_SHA::4}"
          chmod +x docker-build-backend.sh
          bash docker-build-backend.sh
      - name: upload backend
        run: |
          cd backend
          export GIT_COMMIT="GA-${GITHUB_SHA::4}"
          chmod +x docker-push-backend.sh
          bash docker-push-backend.sh

  Docker-build-and-push-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build frontend
        run: |
          cd frontend
          export GIT_COMMIT="GA-${GITHUB_SHA::4}"
          chmod +x docker-build-frontend.sh
          bash docker-build-frontend.sh
      - name: upload frontend
        run: |
          cd frontend
          export GIT_COMMIT="GA-${GITHUB_SHA::4}"
          chmod +x docker-push-frontend.sh
          bash docker-push-frontend.sh

  life-check:
    needs: [Docker-build-and-push-backend, Docker-build-and-push-frontend]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker-compose
      run: |
        export GIT_COMMIT="GA-${GITHUB_SHA::4}"
        docker-compose up -d
        sleep 5
    - name: test availability
      run: bash test.sh

