env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
  
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.17
    steps:
    - uses: actions/checkout@v2

    - name: Build backend
      run: |
        cd backend
        go build -v
    - name: Build frontend
      run: |
        cd frontend
        go build -v
  
  Docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build backend
        run: |
          cd backend
          export GIT_COMMIT="GA-$GITHUB_SHA"
          chmod +x docker-build.backend.sh
          docker-build.backend.sh
      - name: upload backend
        run: |
          cd backend
          export GIT_COMMIT="GA-$GITHUB_SHA"
          chmod +x docker-push.backend.sh
          docker-push.backend.sh




  lint-test:
    runs-on: ubuntu-latest
    container: golang:1.17
    steps:
    - uses: actions/checkout@v2

    - name: lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.0
        cd frontend
        $(go env GOPATH)/bin/golangci-lint run -D errcheck -D gosimple

    - name: Test
      run: |
        cd frontend
        go test -v
        
  life-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run docker-compose
      run: |
        docker-compose up -d
        sleep 5
    - name: test availability
      run: bash test.sh

